server:
  port: 16666
spring:
  application:
    name: gateway
  cloud:
    gateway:
      #配置请求路由
      routes:
        - uri: lb://web-back
          predicates:
            - Path=/back/**
          filters:
            #配置一个自带的过滤器，该过滤器的作用表示会过滤掉请求的第一层路径
            - StripPrefix=1